name: Release
on:
  repository_dispatch:
    types: [rollingversions_publish_approved]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd repo && yarn install --forzen-lockfile
      - run: cd repo && yarn build
      - run: cd repo && yarn lint
      - run: cd repo && yarn prettier:check
      - run: cd repo && yarn test
      - run: cd repo && npm pack
      - run: cp -r repo/test test
      - run: cd test && npm i ../repo/then-retry-0.0.0.tgz
      - run: cd test && node index

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --forzen-lockfile
      - run: yarn build
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npx rollingversions publish --github-token ${{ secrets.GITHUB_TOKEN }}
